In [3]:
import SRC
import os
from SRC.helpFolder import make_weather_data_dataframe, get_weather_data_for_city, append_to_json_file

metadata = SRC.load_model_metadata()

In [4]:
metadata['weatherInformation']

{'archive_api': 'https://archive-api.open-meteo.com/v1/archive',
 'forecast_api': 'https://api.open-meteo.com/v1/forecast',
 'default_city': 'Marrakech',
 'archive_json_path': '../Data/WeatherData/weather_data.json',
 'weather_end_date': '2025-07-20'}

In [5]:
weather_data = get_weather_data_for_city(
    start_date=metadata['PMSInformation']['start_date_range'],
    end_date=metadata['weatherInformation']['weather_end_date'],
    city=metadata['weatherInformation']['default_city']
)

weather_data

Date range spans past and future - making separate requests
Fetching historical data: 2024-05-01 to 2025-07-11
Coordinates 31.59929656982422°N -7.97607421875°E
Elevation 468.0 m asl
Timezone NoneNone
Successfully fetched weather data for 437 dates
Fetching forecast data: 2025-07-12 to 2025-07-20
Coordinates 31.625°N -8.0°E
Elevation 468.0 m asl
Timezone NoneNone
Successfully fetched weather data for 9 dates

{'2024-05-01': {'temperature_max': 26.325998306274414,
  'temperature_min': 10.675999641418457,
  'temperature_mean': 17.948915481567383,
  'precipitation': 0.0,
  'windspeed_max': 13.556282043457031},
 '2024-05-02': {'temperature_max': 27.275999069213867,
  'temperature_min': 11.12600040435791,
  'temperature_mean': 19.28849983215332,
  'precipitation': 0.0,
  'windspeed_max': 13.397611618041992},
 '2024-05-03': {'temperature_max': 31.875999450683594,
  'temperature_min': 10.72599983215332,
  'temperature_mean': 21.57600212097168,
  'precipitation': 0.0,
  'windspeed_max': 11.54247760772705},
 '2024-05-04': {'temperature_max': 33.676002502441406,
  'temperature_min': 17.125999450683594,
  'temperature_mean': 24.37183380126953,
  'precipitation': 0.0,
  'windspeed_max': 17.69867706298828},
 '2024-05-05': {'temperature_max': 33.47600173950195,
  'temperature_min': 14.076000213623047,
  'temperature_mean': 23.648916244506836,
  'precipitation': 0.0,
  'windspeed_max': 20.188907623291016},
 '2024-05-06': {'temperature_max': 31.575998306274414,
  'temperature_min': 16.47599983215332,
  'temperature_mean': 23.50933265686035,
  'precipitation': 0.0,
  'windspeed_max': 17.02689552307129},
 '2024-05-07': {'temperature_max': 34.7760009765625,
  'temperature_min': 15.47599983215332,
  'temperature_mean': 25.23016357421875,
  'precipitation': 0.0,
  'windspeed_max': 15.192682266235352},
 '2024-05-08': {'temperature_max': 36.426002502441406,
  'temperature_min': 16.525999069213867,
  'temperature_mean': 26.598915100097656,
  'precipitation': 0.0,
  'windspeed_max': 15.294703483581543},
 '2024-05-09': {'temperature_max': 36.875999450683594,
  'temperature_min': 18.67599868774414,
  'temperature_mean': 28.66766929626465,
  'precipitation': 0.0,
  'windspeed_max': 17.90253448486328},
 '2024-05-10': {'temperature_max': 33.676002502441406,
  'temperature_min': 20.42599868774414,
  'temperature_mean': 25.91558265686035,
  'precipitation': 0.0,
  'windspeed_max': 15.02110481262207},
 '2024-05-11': {'temperature_max': 32.97600173950195,
  'temperature_min': 18.375999450683594,
  'temperature_mean': 24.69474983215332,
  'precipitation': 0.0,
  'windspeed_max': 15.844090461730957},
 '2024-05-12': {'temperature_max': 31.875999450683594,
  'temperature_min': 15.776000022888184,
  'temperature_mean': 23.0572509765625,
  'precipitation': 0.0,
  'windspeed_max': 14.764389038085938},
 '2024-05-13': {'temperature_max': 32.375999450683594,
  'temperature_min': 15.62600040435791,
  'temperature_mean': 23.253084182739258,
  'precipitation': 0.0,
  'windspeed_max': 15.188414573669434},
 '2024-05-14': {'temperature_max': 29.42599868774414,
  'temperature_min': 14.925999641418457,
  'temperature_mean': 21.138498306274414,
  'precipitation': 0.0,
  'windspeed_max': 17.581125259399414},
 '2024-05-15': {'temperature_max': 26.775999069213867,
  'temperature_min': 14.12600040435791,
  'temperature_mean': 19.448917388916016,
  'precipitation': 0.0,
  'windspeed_max': 20.3168888092041},
 '2024-05-16': {'temperature_max': 28.625999450683594,
  'temperature_min': 11.675999641418457,
  'temperature_mean': 19.72599983215332,
  'precipitation': 0.0,
  'windspeed_max': 15.480000495910645},
 '2024-05-17': {'temperature_max': 28.375999450683594,
  'temperature_min': 12.576000213623047,
  'temperature_mean': 20.25724983215332,
  'precipitation': 0.0,
  'windspeed_max': 14.154914855957031},
 '2024-05-18': {'temperature_max': 24.47599983215332,
  'temperature_min': 15.776000022888184,
  'temperature_mean': 19.6843318939209,
  'precipitation': 0.0,
  'windspeed_max': 12.889809608459473},
 '2024-05-19': {'temperature_max': 22.375999450683594,
  'temperature_min': 14.526000022888184,
  'temperature_mean': 17.826000213623047,
  'precipitation': 0.30000001192092896,
  'windspeed_max': 17.163354873657227},
 '2024-05-20': {'temperature_max': 25.775999069213867,
  'temperature_min': 12.076000213623047,
  'temperature_mean': 18.984333038330078,
  'precipitation': 0.0,
  'windspeed_max': 18.486621856689453},
 '2024-05-21': {'temperature_max': 27.825998306274414,
  'temperature_min': 11.47599983215332,
  'temperature_mean': 19.596834182739258,
  'precipitation': 0.0,
  'windspeed_max': 16.57564353942871},
 '2024-05-22': {'temperature_max': 28.775999069213867,
  'temperature_min': 11.97599983215332,
  'temperature_mean': 20.426000595092773,
  'precipitation': 0.0,
  'windspeed_max': 16.215991973876953},
 '2024-05-23': {'temperature_max': 29.42599868774414,
  'temperature_min': 13.526000022888184,
  'temperature_mean': 21.201000213623047,
  'precipitation': 0.0,
  'windspeed_max': 15.905319213867188},
 '2024-05-24': {'temperature_max': 28.525999069213867,
  'temperature_min': 13.826000213623047,
  'temperature_mean': 20.961416244506836,
  'precipitation': 0.0,
  'windspeed_max': 17.651016235351562},
 '2024-05-25': {'temperature_max': 29.125999450683594,
  'temperature_min': 14.72599983215332,
  'temperature_mean': 22.144750595092773,
  'precipitation': 0.0,
  'windspeed_max': 12.98497486114502},
 '2024-05-26': {'temperature_max': 32.7760009765625,
  'temperature_min': 15.97599983215332,
  'temperature_mean': 24.217668533325195,
  'precipitation': 0.0,
  'windspeed_max': 13.698933601379395},
 '2024-05-27': {'temperature_max': 34.625999450683594,
  'temperature_min': 16.47599983215332,
  'temperature_mean': 25.490583419799805,
  'precipitation': 0.0,
  'windspeed_max': 13.441070556640625},
 '2024-05-28': {'temperature_max': 37.57600021362305,
  'temperature_min': 17.72599983215332,
  'temperature_mean': 27.355165481567383,
  'precipitation': 0.0,
  'windspeed_max': 16.87013816833496},
 '2024-05-29': {'temperature_max': 40.625999450683594,
  'temperature_min': 18.17599868774414,
  'temperature_mean': 28.47599983215332,
  'precipitation': 0.0,
  'windspeed_max': 27.15316390991211},
 '2024-05-30': {'temperature_max': 35.2760009765625,
  'temperature_min': 18.775999069213867,
  'temperature_mean': 27.69683265686035,
  'precipitation': 0.10000000149011612,
  'windspeed_max': 16.61079216003418},
 '2024-05-31': {'temperature_max': 34.7760009765625,
  'temperature_min': 17.825998306274414,
  'temperature_mean': 25.955162048339844,
  'precipitation': 0.0,
  'windspeed_max': 19.586116790771484},
 '2024-06-01': {'temperature_max': 36.5260009765625,
  'temperature_min': 19.17599868774414,
  'temperature_mean': 27.455167770385742,
  'precipitation': 0.0,
  'windspeed_max': 16.071491241455078},
 '2024-06-02': {'temperature_max': 35.926002502441406,
  'temperature_min': 18.67599868774414,
  'temperature_mean': 26.440582275390625,
  'precipitation': 0.0,
  'windspeed_max': 16.56391143798828},
 '2024-06-03': {'temperature_max': 31.17599868774414,
  'temperature_min': 17.17599868774414,
  'temperature_mean': 24.021833419799805,
  'precipitation': 0.0,
  'windspeed_max': 11.885453224182129},
 '2024-06-04': {'temperature_max': 31.47599983215332,
  'temperature_min': 17.025999069213867,
  'temperature_mean': 23.813499450683594,
  'precipitation': 0.0,
  'windspeed_max': 15.51762866973877},
 '2024-06-05': {'temperature_max': 33.625999450683594,
  'temperature_min': 18.275999069213867,
  'temperature_mean': 25.521833419799805,
  'precipitation': 0.0,
  'windspeed_max': 15.315873146057129},
 '2024-06-06': {'temperature_max': 30.275999069213867,
  'temperature_min': 18.025999069213867,
  'temperature_mean': 23.513498306274414,
  'precipitation': 0.0,
  'windspeed_max': 19.242326736450195},
 '2024-06-07': {'temperature_max': 25.025999069213867,
  'temperature_min': 16.42599868774414,
  'temperature_mean': 20.31141471862793,
  'precipitation': 0.0,
  'windspeed_max': 11.212135314941406},
 '2024-06-08': {'temperature_max': 28.97599983215332,
  'temperature_min': 15.276000022888184,
  'temperature_mean': 21.705167770385742,
  'precipitation': 0.0,
  'windspeed_max': 19.130874633789062},
 '2024-06-09': {'temperature_max': 29.17599868774414,
  'temperature_min': 17.125999450683594,
  'temperature_mean': 22.236413955688477,
  'precipitation': 0.0,
  'windspeed_max': 21.077686309814453},
 '2024-06-10': {'temperature_max': 27.125999450683594,
  'temperature_min': 16.97599983215332,
  'temperature_mean': 21.301000595092773,
  'precipitation': 0.10000000149011612,
  'windspeed_max': 16.99260902404785},
 '2024-06-11': {'temperature_max': 29.275999069213867,
  'temperature_min': 17.375999450683594,
  'temperature_mean': 22.02808380126953,
  'precipitation': 0.30000001192092896,
  'windspeed_max': 14.399999618530273},
 '2024-06-12': {'temperature_max': 29.17599868774414,
  'temperature_min': 17.125999450683594,
  'temperature_mean': 22.267667770385742,
  'precipitation': 0.0,
  'windspeed_max': 15.188414573669434},
 '2024-06-13': {'temperature_max': 31.17599868774414,
  'temperature_min': 15.826000213623047,
  'temperature_mean': 23.544748306274414,
  'precipitation': 0.0,
  'windspeed_max': 12.979984283447266},
 '2024-06-14': {'temperature_max': 32.7760009765625,
  'temperature_min': 17.97599983215332,
  'temperature_mean': 25.023916244506836,
  'precipitation': 0.5,
  'windspeed_max': 17.418195724487305},
 '2024-06-15': {'temperature_max': 32.5260009765625,
  'temperature_min': 16.17599868774414,
  'temperature_mean': 23.861413955688477,
  'precipitation': 0.30000001192092896,
  'windspeed_max': 15.683775901794434},
 '2024-06-16': {'temperature_max': 34.0260009765625,
  'temperature_min': 16.025999069213867,
  'temperature_mean': 24.43433380126953,
  'precipitation': 0.0,
  'windspeed_max': 14.973575592041016},
 '2024-06-17': {'temperature_max': 33.47600173950195,
  'temperature_min': 16.72599983215332,
  'temperature_mean': 24.863500595092773,
  'precipitation': 0.0,
  'windspeed_max': 12.43433952331543},
 '2024-06-18': {'temperature_max': 30.22599983215332,
  'temperature_min': 16.575998306274414,
  'temperature_mean': 23.221832275390625,
  'precipitation': 0.0,
  'windspeed_max': 13.493998527526855},
 '2024-06-19': {'temperature_max': 28.375999450683594,
  'temperature_min': 17.72599983215332,
  'temperature_mean': 22.032249450683594,
  'precipitation': 0.4000000059604645,
  'windspeed_max': 16.923830032348633},
 '2024-06-20': {'temperature_max': 29.825998306274414,
  'temperature_min': 15.22599983215332,
  'temperature_mean': 22.08641242980957,
  'precipitation': 0.0,
  'windspeed_max': 17.283748626708984},
 '2024-06-21': {'temperature_max': 33.625999450683594,
  'temperature_min': 14.72599983215332,
  'temperature_mean': 23.940584182739258,
  'precipitation': 0.0,
  'windspeed_max': 17.10662841796875},
 '2024-06-22': {'temperature_max': 38.07600021362305,
  'temperature_min': 17.825998306274414,
  'temperature_mean': 27.807249069213867,
  'precipitation': 0.0,
  'windspeed_max': 12.101570129394531},
 '2024-06-23': {'temperature_max': 41.22600173950195,
  'temperature_min': 21.025999069213867,
  'temperature_mean': 31.336416244506836,
  'precipitation': 0.0,
  'windspeed_max': 14.799459457397461},
 '2024-06-24': {'temperature_max': 39.125999450683594,
  'temperature_min': 20.875999450683594,
  'temperature_mean': 29.54266357421875,
  'precipitation': 0.0,
  'windspeed_max': 15.111424446105957},
 '2024-06-25': {'temperature_max': 33.176002502441406,
  'temperature_min': 18.775999069213867,
  'temperature_mean': 25.54058265686035,
  'precipitation': 0.0,
  'windspeed_max': 16.422470092773438},
 '2024-06-26': {'temperature_max': 26.775999069213867,
  'temperature_min': 18.025999069213867,
  'temperature_mean': 22.088499069213867,
  'precipitation': 0.0,
  'windspeed_max': 14.058449745178223},
 '2024-06-27': {'temperature_max': 27.97599983215332,
  'temperature_min': 17.47599983215332,
  'temperature_mean': 21.361417770385742,
  'precipitation': 0.0,
  'windspeed_max': 17.10662841796875},
 '2024-06-28': {'temperature_max': 29.97599983215332,
  'temperature_min': 16.525999069213867,
  'temperature_mean': 22.907249450683594,
  'precipitation': 0.0,
  'windspeed_max': 11.525623321533203},
 '2024-06-29': {'temperature_max': 33.0260009765625,
  'temperature_min': 17.025999069213867,
  'temperature_mean': 24.838502883911133,
  'precipitation': 0.0,
  'windspeed_max': 15.188414573669434},
 '2024-06-30': {'temperature_max': 34.375999450683594,
  'temperature_min': 17.625999450683594,
  'temperature_mean': 25.4322509765625,
  'precipitation': 0.0,
  'windspeed_max': 16.203998565673828},
 '2024-07-01': {'temperature_max': 34.875999450683594,
  'temperature_min': 17.22599983215332,
  'temperature_mean': 25.767663955688477,
  'precipitation': 0.0,
  'windspeed_max': 13.755579948425293},
 '2024-07-02': {'temperature_max': 36.97600173950195,
  'temperature_min': 17.875999450683594,
  'temperature_mean': 27.042665481567383,
  'precipitation': 0.0,
  'windspeed_max': 14.118243217468262},
 '2024-07-03': {'temperature_max': 36.926002502441406,
  'temperature_min': 19.42599868774414,
  'temperature_mean': 28.00516700744629,
  'precipitation': 0.0,
  'windspeed_max': 13.684735298156738},
 '2024-07-04': {'temperature_max': 36.0260009765625,
  'temperature_min': 19.525999069213867,
  'temperature_mean': 27.471834182739258,
  'precipitation': 0.0,
  'windspeed_max': 18.35999870300293},
 '2024-07-05': {'temperature_max': 33.426002502441406,
  'temperature_min': 18.275999069213867,
  'temperature_mean': 25.463499069213867,
  'precipitation': 0.0,
  'windspeed_max': 14.843179702758789},
 '2024-07-06': {'temperature_max': 33.375999450683594,
  'temperature_min': 17.825998306274414,
  'temperature_mean': 24.957250595092773,
  'precipitation': 0.0,
  'windspeed_max': 14.843179702758789},
 '2024-07-07': {'temperature_max': 32.47600173950195,
  'temperature_min': 17.325998306274414,
  'temperature_mean': 24.330169677734375,
  'precipitation': 0.0,
  'windspeed_max': 16.235960006713867},
 '2024-07-08': {'temperature_max': 32.47600173950195,
  'temperature_min': 16.025999069213867,
  'temperature_mean': 23.953086853027344,
  'precipitation': 0.0,
  'windspeed_max': 17.639999389648438},
 '2024-07-09': {'temperature_max': 35.97600173950195,
  'temperature_min': 17.67599868774414,
  'temperature_mean': 26.3385009765625,
  'precipitation': 0.0,
  'windspeed_max': 15.192682266235352},
 '2024-07-10': {'temperature_max': 41.7760009765625,
  'temperature_min': 19.92599868774414,
  'temperature_mean': 30.350996017456055,
  'precipitation': 0.0,
  'windspeed_max': 14.799459457397461},
 '2024-07-11': {'temperature_max': 44.176002502441406,
  'temperature_min': 20.275999069213867,
  'temperature_mean': 32.125999450683594,
  'precipitation': 0.0,
  'windspeed_max': 19.272613525390625},
 '2024-07-12': {'temperature_max': 44.125999450683594,
  'temperature_min': 21.67599868774414,
  'temperature_mean': 32.51350021362305,
  'precipitation': 0.0,
  'windspeed_max': 14.843179702758789},
 '2024-07-13': {'temperature_max': 40.07600021362305,
  'temperature_min': 22.72599983215332,
  'temperature_mean': 31.02808380126953,
  'precipitation': 0.0,
  'windspeed_max': 12.096214294433594},
 '2024-07-14': {'temperature_max': 41.57600021362305,
  'temperature_min': 21.075998306274414,
  'temperature_mean': 31.20099639892578,
  'precipitation': 0.0,
  'windspeed_max': 12.413476943969727},
 '2024-07-15': {'temperature_max': 38.625999450683594,
  'temperature_min': 21.72599983215332,
  'temperature_mean': 29.638504028320312,
  'precipitation': 0.0,
  'windspeed_max': 15.496735572814941},
 '2024-07-16': {'temperature_max': 37.57600021362305,
  'temperature_min': 19.875999450683594,
  'temperature_mean': 28.3697509765625,
  'precipitation': 0.0,
  'windspeed_max': 13.397611618041992},
 '2024-07-17': {'temperature_max': 39.676002502441406,
  'temperature_min': 21.125999450683594,
  'temperature_mean': 30.748916625976562,
  'precipitation': 0.0,
  'windspeed_max': 13.397611618041992},
 '2024-07-18': {'temperature_max': 42.926002502441406,
  'temperature_min': 24.42599868774414,
  'temperature_mean': 33.5885009765625,
  'precipitation': 0.0,
  'windspeed_max': 26.57668113708496},
 '2024-07-19': {'temperature_max': 44.426002502441406,
  'temperature_min': 26.075998306274414,
  'temperature_mean': 35.17183303833008,
  'precipitation': 0.0,
  'windspeed_max': 20.570463180541992},
 '2024-07-20': {'temperature_max': 41.176002502441406,
  'temperature_min': 26.97599983215332,
  'temperature_mean': 33.09475326538086,
  'precipitation': 0.0,
  'windspeed_max': 17.294992446899414},
 '2024-07-21': {'temperature_max': 40.72600173950195,
  'temperature_min': 23.125999450683594,
  'temperature_mean': 31.16766929626465,
  'precipitation': 0.0,
  'windspeed_max': 14.113653182983398},
 '2024-07-22': {'temperature_max': 43.32600021362305,
  'temperature_min': 22.375999450683594,
  'temperature_mean': 33.05308151245117,
  'precipitation': 0.0,
  'windspeed_max': 12.849528312683105},
 '2024-07-23': {'temperature_max': 47.22600173950195,
  'temperature_min': 24.325998306274414,
  'temperature_mean': 35.80933380126953,
  'precipitation': 0.0,
  'windspeed_max': 17.884428024291992},
 '2024-07-24': {'temperature_max': 48.0260009765625,
  'temperature_min': 27.275999069213867,
  'temperature_mean': 38.17599868774414,
  'precipitation': 0.0,
  'windspeed_max': 20.390113830566406},
 '2024-07-25': {'temperature_max': 45.375999450683594,
  'temperature_min': 27.375999450683594,
  'temperature_mean': 36.00307846069336,
  'precipitation': 0.0,
  'windspeed_max': 18.440998077392578},
 '2024-07-26': {'temperature_max': 40.07600021362305,
  'temperature_min': 23.22599983215332,
  'temperature_mean': 31.355165481567383,
  'precipitation': 0.0,
  'windspeed_max': 15.188414573669434},
 '2024-07-27': {'temperature_max': 35.7760009765625,
  'temperature_min': 20.375999450683594,
  'temperature_mean': 27.60099983215332,
  'precipitation': 0.0,
  'windspeed_max': 17.651016235351562},
 '2024-07-28': {'temperature_max': 35.97600173950195,
  'temperature_min': 20.17599868774414,
  'temperature_mean': 27.003084182739258,
  'precipitation': 0.0,
  'windspeed_max': 22.691425323486328},
 '2024-07-29': {'temperature_max': 35.82600021362305,
  'temperature_min': 19.275999069213867,
  'temperature_mean': 27.036415100097656,
  'precipitation': 0.0,
  'windspeed_max': 13.5706148147583},
 '2024-07-30': {'temperature_max': 39.625999450683594,
  'temperature_min': 19.775999069213867,
  'temperature_mean': 29.96558380126953,
  'precipitation': 0.0,
  'windspeed_max': 15.986593246459961},
 '2024-07-31': {'temperature_max': 43.07600021362305,
  'temperature_min': 23.47599983215332,
  'temperature_mean': 33.073917388916016,
  'precipitation': 0.0,
  'windspeed_max': 14.689587593078613},
 '2024-08-01': {'temperature_max': 43.0260009765625,
  'temperature_min': 25.575998306274414,
  'temperature_mean': 33.26142120361328,
  'precipitation': 0.0,
  'windspeed_max': 16.57564353942871},
 '2024-08-02': {'temperature_max': 42.125999450683594,
  'temperature_min': 24.875999450683594,
  'temperature_mean': 32.742671966552734,
  'precipitation': 0.0,
  'windspeed_max': 14.5610990524292},
 '2024-08-03': {'temperature_max': 42.47600173950195,
  'temperature_min': 22.67599868774414,
  'temperature_mean': 32.43850326538086,
  'precipitation': 0.0,
  'windspeed_max': 14.039999961853027},
 '2024-08-04': {'temperature_max': 43.22600173950195,
  'temperature_min': 22.92599868774414,
  'temperature_mean': 32.855167388916016,
  'precipitation': 0.0,
  'windspeed_max': 14.812589645385742},
 '2024-08-05': {'temperature_max': 38.926002502441406,
  'temperature_min': 22.47599983215332,
  'temperature_mean': 30.02808380126953,
  'precipitation': 0.0,
  'windspeed_max': 15.141413688659668},
 '2024-08-06': {'temperature_max': 37.72600173950195,
  'temperature_min': 20.375999450683594,
  'temperature_mean': 28.72808265686035,
  'precipitation': 0.0,
  'windspeed_max': 13.493998527526855},
 '2024-08-07': {'temperature_max': 37.82600021362305,
  'temperature_min': 20.125999450683594,
  'temperature_mean': 28.67183494567871,
  'precipitation': 0.0,
  'windspeed_max': 12.101570129394531},
 '2024-08-08': {'temperature_max': 38.57600021362305,

In [8]:
append_to_json_file(
    weather_data,
    '../Data/WeatherData/weather_data.json',
)

In [9]:
import json

with open('../Data/WeatherData/weather_data.json', 'w', encoding='utf-8') as f:
    json.dump(weather_data, f, indent=4, ensure_ascii=False)

In [5]:
df.head()

,temperature_max,temperature_min,temperature_mean,precipitation,windspeed_max,temperature_range,has_precipitation,precipitation_category,wind_category,day_of_week
date,,,,,,,,,,
2024-05-01,26.326,10.676,17.949,0.0,13.556,15.65,False,None,Moderate,Wednesday
2024-05-02,27.276,11.126,19.288,0.0,13.398,16.15,False,None,Moderate,Thursday
2024-05-03,31.876,10.726,21.576,0.0,11.542,21.15,False,None,Moderate,Friday
2024-05-04,33.676,17.126,24.372,0.0,17.699,16.55,False,None,Moderate,Saturday
2024-05-05,33.476,14.076,23.649,0.0,20.189,19.40,False,None,Strong,Sunday

In [6]:
df.tail()

,temperature_max,temperature_min,temperature_mean,precipitation,windspeed_max,temperature_range,has_precipitation,precipitation_category,wind_category,day_of_week
date,,,,,,,,,,
2025-06-03,35.225,20.875,27.085,0.0,28.358,14.35,False,None,Strong,Tuesday
2025-06-04,31.275,18.875,24.531,0.0,24.313,12.40,False,None,Strong,Wednesday
2025-06-05,31.325,17.125,23.673,0.0,27.757,14.20,False,None,Strong,Thursday
2025-06-06,35.025,18.525,26.279,0.0,15.282,16.50,False,None,Moderate,Friday
2025-06-07,40.225,20.825,30.460,0.0,18.775,19.40,False,None,Moderate,Saturday