In [4]:
from dotenv import load_dotenv # type: ignore
import os 
import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import SRC
from SRC.helpFolder import *

metaData = SRC.load_model_metadata()

In [2]:
segement_data = load_json_data('../../Data/SegmentMetricsData/segments_metrics.json')

In [5]:
def transform_to_dataframe(data):
    """
    Transforms the input data dictionary into a Pandas DataFrame.

    Args:
        data (dict): A dictionary structured with dates as keys, 
                     and nested dictionaries for segments and their metrics.
    """
    records = []
    for date, segments_data in data.items():
        for segment, metrics in segments_data.items():
            records.append({
                'date': date,
                'segment': segment,
                'taux_occupation': metrics.get('Occupancy percentage'),
                'total_price': metrics.get('Revenue')
            })
    df = pd.DataFrame(records)
    return df

In [6]:
df =transform_to_dataframe(segement_data)

In [8]:
df.head(10)

         date       segment  taux_occupation  total_price
0  2024-05-01           AVM             0.23      1320.00
1  2024-05-01            TO             0.93     12619.36
2  2024-05-01  Onlines(OTA)             0.00         0.00
3  2024-05-01           CRS             0.00         0.00
4  2024-05-01           VCR             0.00         0.00
5  2024-05-01        WalkIn             0.00         0.00
6  2024-05-01           Web             0.00         0.00
7  2024-05-01           B2B             0.23       108.80
8  2024-05-01          comp             0.00         0.00
9  2024-05-02           AVM             0.46      2970.00

In [9]:
df = preprocess_for_forecasting(df)

In [11]:
df.head(10)

,segment,taux_occupation,total_price,dayofweek,month,year,dayofyear,weekofyear
date,,,,,,,,
2024-05-01,AVM,0.23,1320.00,2,5,2024,122,18
2024-05-01,TO,0.93,12619.36,2,5,2024,122,18
2024-05-01,Onlines(OTA),0.00,0.00,2,5,2024,122,18
2024-05-01,CRS,0.00,0.00,2,5,2024,122,18
2024-05-01,VCR,0.00,0.00,2,5,2024,122,18
2024-05-01,WalkIn,0.00,0.00,2,5,2024,122,18
2024-05-01,Web,0.00,0.00,2,5,2024,122,18
2024-05-01,B2B,0.23,108.80,2,5,2024,122,18
2024-05-01,comp,0.00,0.00,2,5,2024,122,18
2024-05-02,AVM,0.46,2970.00,3,5,2024,123,18

In [13]:
df.columns

Index(['segment', 'taux_occupation', 'total_price', 'dayofweek', 'month',
       'year', 'dayofyear', 'weekofyear'],
      dtype='object')